### ISSUE TITLE
pass token when calling webhook api

### ISSUE THREAD

**Issue by shreyas-shinde** [StackStorm-Exchange/stackstorm-zabbix#14]
https://github.com/StackStorm-Exchange/stackstorm-zabbix/blob/master/tools/scripts/st2_dispatch.py#L31

Like below:
self.client.managers['Webhook'].client.post('/webhooks/st2', body, token=self.client.token)

i can see in my api log no token or api key given error.

**Comment by LindsayHill** [comment]
Can you create a PR to fix this?
