### ISSUE TITLE
Zabbix 4.0 is released

### ISSUE THREAD

**Issue by shreyas-shinde** [StackStorm-Exchange/stackstorm-zabbix#18]
FYI Zabbix 4.0 is released. https://www.zabbix.com/documentation/4.0/manual/introduction/whatsnew400

**Comment by userlocalhost** [comment]
Thank you for notification. I should be able to verify all functionality in this pack is available, or not, at Zabbix 4.0.

**Comment by shreyas-shinde** [comment]
Hi do you have any schedule by when you will be able to do above testing? Thanks

**Comment by iwillneverstop** [comment]
I'm also interested in this new Zabbix version.

**Comment by userlocalhost** [comment]
Thank you for giving me remind. I have no schedule but I want to get down to this from this week.

BTW, I'm not sure the best practice how to guarantee the compatibility. 
I guess, it needs not only of my assurance but also something like test suite that ensures the functions to work at each supported Zabbix versions.

Firstly, I think we should cover following functions at least.

- whether it is possible to dispatch a trigger from AlertScript of `st2_dispatch.py` normally.
- whether all acripts of this pack are available.

So, I'll write a test suite that includes these items in wiki page. Then, I'll check them.

Please tell me if you have any ideas for this. And it's much appreciated if you help us to check it.

**Comment by LindsayHill** [comment]
> Hi do you have any schedule by when you will be able to do above testing?

@shreyas-shinde you could also do this yourself? Anyone could try using this pack with a test Zabbix 4.x system, and report back here.

> I'm not sure the best practice how to guarantee the compatibility.

Not easy. Sometimes the best you can do is to just rely on the release notes, and see what they say about API changes

**Comment by userlocalhost** [comment]
I made a checklist to ensure that target Zabbix is capable of being integrated with this pack.
https://github.com/StackStorm-Exchange/stackstorm-zabbix/wiki/Check-List-of-Compatibility

By increasing the functionality of this pack, this list will also be grew up, maybe.

Eventually, I hope to do by running integration test suites.
I have no good idea for it yet, but I want to seek it by referring [Tempest](https://docs.openstack.org/tempest/latest/).

Anyway, I'll check it in my environment and keep track of the result to here.

**Comment by nmaludy** [comment]
@userlocalhost For integration tests we could potentially spin up a Docker container with a Zabbix instance, then run actions against that container's API: https://hub.docker.com/r/zabbix/zabbix-server-mysql/

I've done something similar in the Vault authentication module: 

https://github.com/EncoreTechnologies/st2-auth-backend-vault

Vagrantfile used to spin up the Docker container: https://github.com/EncoreTechnologies/st2-auth-backend-vault/blob/master/Vagrantfile

Example integration test: https://github.com/EncoreTechnologies/st2-auth-backend-vault/blob/master/tests/integration/base.py

**Comment by userlocalhost** [comment]
@nmaludy Cooooooool!!! Thank you!!

**Comment by iwillneverstop** [comment]
We (shreyas-shinde and I) met and we decided to test it for you. We could confirm that this pack is compatible with Zabbix 4.0. Thank you for this pack.

**Comment by LindsayHill** [comment]
Thank you @iwillneverstop - that's a great help. I have updated the README to include v4.0
