### ISSUE TITLE
Little mistake in description

### ISSUE THREAD

**Issue by nikolaev-rd** [StackStorm-Exchange/stackstorm-zabbix#26]
Not `uername` but `username`
https://github.com/StackStorm-Exchange/stackstorm-zabbix/blob/163c74b777172fad3b25a5e38fa5a0a22d2a1189/tools/register_st2_config_to_zabbix.py#L64

**Comment by nikolaev-rd** [comment]
Also on [screenshot](https://github.com/StackStorm-Exchange/stackstorm-zabbix/blob/master/images/configuration_for_mediatype2.png).

**Comment by Kami** [comment]
Thanks for reporting this.

Feel free to open a pull request which fixes this typo in ``stackstorm-zabbix/tools/register_st2_config_to_zabbix.py`` file.
