### ISSUE TITLE
user.addmedia is deprecated in Zabbix 4.0

### ISSUE THREAD

**Issue by thebeerman** [StackStorm-Exchange/stackstorm-zabbix#28]
When running register_st2_config_to_zabbix.py against a Zabbix 4.x installation, the script fails trying to add a user media.  
Per Zabbix 3.4 documentation https://www.zabbix.com/documentation/3.4/manual/api/reference/user/addmedia
"This method is deprecated and will be removed in the future. Please use user.update instead."

Error when running the script
pyzabbix.api.ZabbixAPIException: ('Error -32602: Invalid params., Incorrect method "user.addmedia". while sending ......

**Comment by userlocalhost** [comment]
Sorry for late to reply and thank you for telling it. I confirm this problem. And I should be able to fix it.
