### ISSUE TITLE
ack_event.yaml - param `will_close` enum with boolean type

### ISSUE THREAD

**Issue by namachieli** [StackStorm-Exchange/stackstorm-zabbix#32]
The action `ack_event.yaml` has a parameter `will_close` with `type: boolean` but also has enum of `True, False`. When trying to use this action in the webgui it presents a list of strings for "True" and "False" but will not accept the input because it is a string, not a boolean.

Recommendation: remove `enum:` and leave default (true) as is.

**Comment by LindsayHill** [comment]
Sounds good. Am a little surprised that this passed validation OK.

**Comment by namachieli** [comment]
I can include this in my PR I'm working on, or it can be separate.

**Comment by LindsayHill** [comment]
Add it in your one if you like. Small enough change
