### ISSUE TITLE
Create CODEOWNERS file

### ISSUE THREAD

**Issue by userlocalhost** [StackStorm-Exchange/stackstorm-zabbix#42]
TSC members promote to put CODEOWNERS flie in this repository(c.f. https://github.com/StackStorm-Exchange/exchange-incubator/issues/152). This issue puts together what kind of contents we should make.

**Comment by userlocalhost** [comment]
I want to discuss about who will be listed on CODEOWNERS in this issue. In other words, who will be responsible for which files. 
For the time being, I could be responsible for all the files.

@namachieli 
Would you like to be responsible for whole code or part of it?

And, would any contributors who can be listed on CODEOWNERS please give us comment in this issue?

**Comment by armab** [comment]
Based on current repository permissions and members here is how the `.github/CODEOWNERS` might look like:

```
*            @userlocalhost @namachieli @StackStorm-Exchange/encoretechnologies @StackStorm-Exchange/tsc
.circleci/** @StackStorm-Exchange/tsc
```
