### ISSUE TITLE
Hei,how to add config?

### ISSUE THREAD

**Issue by woodywuuu** [StackStorm-Exchange/stackstorm-zabbix#6]
I'm new to st2 and zabbix.
When I try to run **zabbix.test_credentials** ,it need data from configuration.I even check **class Action** in st2common,but can't find anything about where to add config.So I write a config dict in actions.py .XD

**Comment by killsudo** [comment]
You need to copy and rename the following file inside /opt/stackstorm/packs/zabbix/zabbix.yaml.example to /opt/stackstorm/configs/zabbix.yaml

Example:
https://github.com/StackStorm-Exchange/stackstorm-zabbix/blob/master/zabbix.yaml.example

**Comment by userlocalhost** [comment]
Thank you for prompt answer, @killsudo.

In addition, you also need to execute following command after setting `/opt/stackstorm/configs/zabbix.yaml` file to register the configuration to the datastore.
```
# st2ctl reload --register-configs
```
or

You should configure the zabbix pack interactively as below. it's equal to the upper processings.
```
$ st2 pack config zabbix
```

**Comment by woodywuuu** [comment]
Thank you ! @killsudo @userlocalhost
